### ISSUE TITLE
Protect against overflow during block assembly

### ISSUE THREAD

**Issue by JBetz** [SequentiaSEQ/SEQ-Core-Elements#9]
During block assembly, all transaction fees are combined into a single vout for the coinbase transaction. When issued assets are used for fees there's a risk of overflow since issued assets may be reissued such that the total supply exceeds MAX_MONEY. This will cause consensus validation of the block to fail, so there's no risk of such blocks being added to the chain, but we need to make sure that block production doesn't halt and that this situation is prevented as much as possible.

One solution might be to split fees into multiple outputs such that they individually never exceed MAX_MONEY. A more ambitious solution would prevent token supply of any given asset never exceeding MAX_MONEY, possibly as an external mechanism that would allow it to be addressed as a social rather than technical problem.

**Comment by fare** [comment]
It is important that the miner software should not be DoS'ed in case someone creates more than MAX_MONEY of an accepted fee asset.

Possible protective measures:
- While accumulating transactions, detect that a sum of fees in a asset is more than MAX_MONEY, and then reject the last transaction—and maybe even reject all transactions using that asset, retroactively, or for all times future (tag it as not-for-use in the known list)
- Count the total fees as we go, and in the coinbase transaction create multiple vouts for the asset, each under MAX_MONEY.

What more:
- If we go the "tag not-for-use" route, we might tag as not-for-use any asset that has a blinded issuance that wasn't unblinded (yet—which requires tracking the so-far-not-unblinded blinded transactions), or whose known issuance total MAX_MONEY or more.
- Either way, we might need to estimate the size of the coinbase tx, and increase it whenever a new fee asset is used; or conversely assume they will all be used (if not too many), and decrease it in the end. Otherwise, we might go over the block limit and produce an invalid block.

This additional points might be considered separate issues when the time comes, but are fixed more or less at the same place.

**Comment by fare** [comment]
Too bad GitHub doesn't have a status for "Closed for now, reopen later", or something.
